volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    depends_on:
      - db
    env_file: .env
    volumes:
      - media:/app/media
      - static:/backend_static
    build: ./backend/
    
  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/
  gateway:
    depends_on:
      - backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 8000:80
    build: ./nginx/
